### ISSUE TITLE
Duplicated issue (issue #1)

### ISSUE THREAD

**Issue by adamnk** [Just-Fans-Of/Impromp2#12]
Is there a way i can tell the bot what server groups is allowed/not allowed,  to join the temporary channel?

**Comment by NumbuhFour** [comment]
Not currently, we're working on that with issue #1

**Comment by adamnk** [comment]
ohh.. sorry for duplicated issue!

**Comment by NumbuhFour** [comment]
That's alright dude, it should be implemented now. Config has a new property called `tempChannelPermissions` which will let you set the permissions of the created channels.

To do this, create a dummy voice channel, set all the roles/member permissions on it that you want your temporary channels to have, then do `/config set tempchannelpermissions YourDummyChannelsName` and it will copy the permissions on that channel and use them for any future created channels. Then you delete that dummy channel.

Hope that helps.
